Repository groomthon-7/FE-ire, pull requests merged in 2023-09, with the labels that each got.

#1 프로젝트 기본 세팅
  IRE/src/App.js
  IRE/src/Redux/action.js
  IRE/src/Redux/reducer.js
  IRE/src/Redux/store.js
  IRE/src/components/common/button.js
  IRE/src/index.js
  IRE/src/researchData.js
Labels: 🐛 bugfix, 📝 documentation

#3 캠핑장리스트 마크업 및 스타일링 구현
  IRE/src/App.css
  IRE/src/App.js
  IRE/src/api/getCampingList.js
  IRE/src/assets/CampingList/Ellipse18.png
  IRE/src/components/CampingList/Button.js
  IRE/src/components/CampingList/Card.js
  IRE/src/pages/CampingList.js
  IRE/src/style/theme.js
Labels: 💄 publishing

#4 Camping list
  IRE/src/pages/CampingList.js
Labels: 💄 publishing

#5 카카오 지도 추가하기
  IRE/.env
  IRE/public/index.html
  IRE/src/App.js
  IRE/src/components/CampingMap/Map.js
  IRE/src/pages/CampingList.js
  IRE/src/pages/CampingMap.js
Labels: ✨ feature

#6 로딩화면 구현
  IRE/src/App.css
  IRE/src/App.js
  IRE/src/assets/Loading/Rolling-1s-244px.gif
  IRE/src/assets/Loading/spin.png
  IRE/src/index.css
  IRE/src/pages/Loading.js
Labels: 💄 publishing
